### ISSUE TITLE
Can't run addon

### ISSUE THREAD

**Issue by BTopbas** [mancuniancol/script.subscription.pulsar.trakt#1]
I have wetek play openelec device(armv7) everythink is normal. Only trakt subsc. addon cant run. I looked log and i found that. What is problem?

20:57:14 T:2951029824   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: Unknown addon id 'script.module.metahandler'.
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.subscription.pulsar.trakt/service.py", line 2, in <module>
                                                from lib.tools import *
                                              File "/storage/.kodi/addons/script.subscription.pulsar.trakt/lib/__init__.py", line 28, in <module>
                                                import common
                                              File "/storage/.kodi/addons/script.subscription.pulsar.trakt/lib/common.py", line 22, in <module>
                                                addon = Addon('script.module.metahandler')
                                              File "/storage/.kodi/addons/script.subscription.pulsar.trakt/lib/addon.py", line 62, in __init__
                                                self.addon = xbmcaddon.Addon(id=addon_id)
                                            RuntimeError: Unknown addon id 'script.module.metahandler'.
                                            -->End of Python script error report<--

**Comment by BTopbas** [comment]
Solved. I install metahandler module and now everything working.

**Comment by mancuniancol** [comment]
Yes, it is a missing dependency, I've added to the addon.xml, though

**Comment by mancuniancol** [comment]
Thank you, btw :)
